name: Basic CI Pipeline

# Trigger the workflow on push and pull requests to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Define jobs that will run
jobs:
  # Job 1: Source and Build
  build:
    name: Build Application
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout source code
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    # Step 2: Setup Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    # Step 3: Install dependencies
    - name: Install Dependencies
      run: npm ci
      
    # Step 4: Build application
    - name: Build Application
      run: npm run build
      
    # Step 5: Upload build artifacts
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: dist/