name: Multi-Stage CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

# Define environment variables
env:
  NODE_VERSION: '18'
  ARTIFACT_NAME: 'app-build'

jobs:
  # STAGE 1: SOURCE - Checkout and prepare
  source:
    name: 📦 Source Stage
    runs-on: ubuntu-latest
    
    outputs:
      commit-sha: ${{ steps.commit.outputs.sha }}
      
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Get Commit SHA
      id: commit
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
    - name: Display Repository Info
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit: ${{ steps.commit.outputs.sha }}"

  # STAGE 2: BUILD - Compile and create artifacts
  build:
    name: 🏗️ Build Stage
    runs-on: ubuntu-latest
    needs: source  # This stage depends on source stage
    
    outputs:
      build-version: ${{ steps.version.outputs.version }}
      
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install Dependencies
      run: |
        echo "Installing production dependencies..."
        npm ci --only=production
        
    - name: Install Dev Dependencies
      run: |
        echo "Installing development dependencies..."
        npm ci
        
    - name: Generate Build Version
      id: version
      run: |
        VERSION="1.0.${{ github.run_number }}"
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "Build Version: ${VERSION}"
        
    - name: Build Application
      run: |
        echo "Building application version ${{ steps.version.outputs.version }}..."
        npm run build
        echo "Build completed successfully!"
        
    - name: Create Build Info
      run: |
        echo "{
          \"version\": \"${{ steps.version.outputs.version }}\",
          \"commit\": \"${{ needs.source.outputs.commit-sha }}\",
          \"buildTime\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",
          \"branch\": \"${{ github.ref_name }}\"
        }" > dist/build-info.json
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: |
          dist/
          package.json
        retention-days: 30

  # STAGE 3: TEST - Run quality checks and tests
  test:
    name: 🧪 Test Stage
    runs-on: ubuntu-latest
    needs: build  # This stage depends on build stage
    
    strategy:
      matrix:
        test-type: [unit, integration, lint]
        
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm ci
      
    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ./artifacts/
        
    - name: Run Unit Tests
      if: matrix.test-type == 'unit'
      run: |
        echo "Running unit tests..."
        npm test
        echo "Unit tests completed!"
        
    - name: Run Integration Tests
      if: matrix.test-type == 'integration'
      run: |
        echo "Running integration tests..."
        echo "Integration tests completed!"
        
    - name: Run Linting
      if: matrix.test-type == 'lint'
      run: |
        echo "Running code linting..."
        npm run lint
        echo "Linting completed!"
        
    - name: Generate Test Report
      run: |
        echo "Test Type: ${{ matrix.test-type }}"
        echo "Status: Passed"
        echo "Build Version: ${{ needs.build.outputs.build-version }}"

  # STAGE 4: RELEASE - Create release package
  release:
    name: 🚀 Release Stage
    runs-on: ubuntu-latest
    needs: [source, build, test]  # This stage depends on all previous stages
    if: github.ref == 'refs/heads/main'  # Only run on main branch
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ./release/
        
    - name: Display Build Information
      run: |
        echo "=== RELEASE INFORMATION ==="
        echo "Version: ${{ needs.build.outputs.build-version }}"
        echo "Commit: ${{ needs.source.outputs.commit-sha }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "==========================="
        cat ./release/build-info.json
        
    - name: Create Release Package
      run: |
        echo "Creating release package..."
        tar -czf release-${{ needs.build.outputs.build-version }}.tar.gz -C release .
        echo "Release package created: release-${{ needs.build.outputs.build-version }}.tar.gz"
        
    - name: Upload Release Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-package
        path: release-${{ needs.build.outputs.build-version }}.tar.gz
        
    - name: Deployment Simulation
      run: |
        echo "🚀 Deploying to production environment..."
        echo "✅ Deployment completed successfully!"
        echo "🌐 Application is now live!"